# Generated by Django 5.0.7 on 2024-07-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("ticket_title", models.TextField()),
                ("ticket_description", models.TextField()),
                ("ticket_state", models.IntegerField(default=0)),
                ("user_name", models.TextField()),
                ("user_phone", models.TextField()),
            ],
        ),
    ]
