# Generated by Django 5.0.7 on 2024-07-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_title",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="user_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="user_phone",
            field=models.CharField(max_length=30),
        ),
    ]
